### ISSUE TITLE
Loading Audio crashes Astrofox

### ISSUE THREAD

**Issue by cameronbosch** [astrofox-io/astrofox#101]
Astrofox goes to a grey screen when I try to load audio from both mp3 & flac audio files. Here is the error output in the terminal on Linux:

`Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at U (/tmp/.mount_AstrofzooI1a/resources/app.asar/main.js:1:266329)
    at BrowserWindow.M (/tmp/.mount_AstrofzooI1a/resources/app.asar/main.js:1:266447)
    at BrowserWindow.emit (node:events:406:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at U (/tmp/.mount_AstrofzooI1a/resources/app.asar/main.js:1:266329)
    at BrowserWindow.M (/tmp/.mount_AstrofzooI1a/resources/app.asar/main.js:1:266447)
    at BrowserWindow.emit (node:events:406:35`

**Comment by mikecao** [comment]
The audio loading path and Electron IPC were rewritten for 2.0; this crash no longer applies.

Closing as resolved in Astrofox 2.0. If you can still reproduce this on 2.x, please open a new issue with steps and your version.
