### ISSUE TITLE
Export bug

### ISSUE THREAD

**Issue by comav** [astrofox-io/astrofox#33]
I created a project, then I clicked "Save video", set up the settings and started to wait. When progress bar hit 100% the app became gray and there is no video file in destination folder.
![image](https://user-images.githubusercontent.com/61016697/105503675-9011bf80-5ccf-11eb-91e3-95414c37686c.png)

**Comment by mikecao** [comment]
What OS are you using?

**Comment by comav** [comment]
Windows 10 2004 x64

**Comment by riverma** [comment]
@mikecao @comav I noticed this exact issue on macOS 10.15.7 with the following export settings:
- 30fps
- Audio m4a file
- mp4 output
- Two scenes
- 10+ layers

Any suggested workarounds?

**Comment by mikecao** [comment]
@riverma Does your export finish even though the app crashes?

**Comment by mikecao** [comment]
Please try the latest version 1.2.0

**Comment by ChetanAmrao** [comment]
Hi Mike, love this project you made!
I was hoping to use it for a short clip, I followed the steps in the readme doc but not able to get the file exported
I am using
- windows 10
- 1 minute mp3 audio clip
- an image and text, also added a wave spectrum to it
when I click save video, i get no response from the app. It goes unresponsive and I wait for an hour but nothing happens till I stop it from the command prompt
could you resolve my issue?

**Comment by mikecao** [comment]
@ChetanAmrao I've never heard of it freezing before. You can bring up the developer console to see if there are any errors thrown.

**Comment by ChetanAmrao** [comment]
Yes, I found that option and got this error.

    `
    app.js:1 astrofox Error: spawn C:\Users\User\Downloads\astrofox\astrofox\bin\ffmpeg.exe ENOENT
    output @ app.js:1
    error @ app.js:1
    start @ app.js:1
    async function (async)
    start @ app.js:1
    (anonymous) @ app.js:1
    setTimeout (async)
    onClick @ app.js:1
    Ge @ app.js:1
    Ye @ app.js:1
    (anonymous) @ app.js:1
    Mr @ app.js:1
    Tr @ app.js:1
    (anonymous) @ app.js:1
    Ie @ app.js:1
    (anonymous) @ app.js:1
    Rr @ app.js:1
    Kt @ app.js:1
    Qt @ app.js:1
    t.unstable_runWithPriority @ app.js:1
    Gi @ app.js:1
    De @ app.js:1
    Zt @ app.js:1
    app.js:1 Uncaught (in promise) Error: spawn C:\Users\User\Downloads\astrofox\astrofox\bin\ffmpeg.exe ENOENT
    async function (async)
    start @ app.js:1
    (anonymous) @ app.js:1
    setTimeout (async)
    onClick @ app.js:1
    Ge @ app.js:1
    Ye @ app.js:1
    (anonymous) @ app.js:1
    Mr @ app.js:1
    Tr @ app.js:1
    (anonymous) @ app.js:1
    Ie @ app.js:1
    (anonymous) @ app.js:1
    Rr @ app.js:1
    Kt @ app.js:1
    Qt @ app.js:1
    t.unstable_runWithPriority @ app.js:1
    Gi @ app.js:1
    De @ app.js:1
    Zt @ app.js:1
    `

**Comment by mikecao** [comment]
@ChetanAmrao are you running the installed application or the repo? It says it can't find ffmpeg.exe and it seems you're running it from a strange location.

**Comment by ChetanAmrao** [comment]
running from my downloads folder and I did install ffmpeg but idk why its giving me that error still

**Comment by riverma** [comment]
> @riverma Does your export finish even though the app crashes?

@mikecao it did not. 

I should mention I did find a workaround: ensuring my audio file was a LAME encoded MP3, not the iTunes M4A, and being methodical to add Astrofox filters right after a fresh restart and then hitting render - not having the program running for some time after previous render job attempts. i.e. "have you turned it off and on again?" ;)

**Comment by ChetanAmrao** [comment]
Now, I did it using ```yarn``` and followed the exact same steps 
it rendered my video and then hangs
at least video was exported but have to run it each time I export now? 🤔

**Comment by erroreyes** [comment]
I just got this when I exported a test video for the first time (I am a first time user), and this is what in the console:

```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (node:electron/js2c/browser_init:165:417)
    at Object.b.send (node:electron/js2c/browser_init:161:2492)
    at U (/tmp/.mount_AstrofZGBZ1g/resources/app.asar/main.js:1:266329)
    at BrowserWindow.M (/tmp/.mount_AstrofZGBZ1g/resources/app.asar/main.js:1:266447)
    at BrowserWindow.emit (node:events:406:35)
```

The export process seems to finish, but no file is ever saved in the directory.

**Comment by mikecao** [comment]
Astrofox 2.0 replaced the old rendering pipeline with an offline, frame-by-frame ffmpeg export (no more real-time capture on desktop). Export now has a progress counter, a Cancel button, and always kills ffmpeg and restores the editor when it finishes or fails.

Closing as resolved in Astrofox 2.0. If you can still reproduce this on 2.x, please open a new issue with steps and your version.
